server:
  port: 8000

# asd
# asd
spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
              - "http://localhost:5173"
              - "https://infolearnplaydata123456.shop"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allow-credentials: true

      routes:
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: order-service
          uri: http://user-service.default.svc.cluster.local:8083
          predicates:
            - Path=/order-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: course-service
          uri: http://user-service.default.svc.cluster.local:8082
          predicates:
            - Path=/course-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/course-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: post-service
          uri: http://user-service.default.svc.cluster.local:8084
          predicates:
            - Path=/post-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: eval-service
          uri: http://user-service.default.svc.cluster.local:8085
          predicates:
            - Path=/eval-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/eval-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter


jwt:
  expiration: 60
  secretKey: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==

  secretKeyRt: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==
  expirationRt: 120